spring.application.name=cart-service
server.port=8081
# Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cartdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.platform=postgresql


#Hikari configurations
spring.datasource.hikari.maximum-pool-size=10
#default 3 ready to use connections in the pool
spring.datasource.hikari.minimum-idle=3
#30s waiting period for requests or api calls
spring.datasource.hikari.connection-timeout=30000
#Time for connections after this interval the connection with database is closed i.e. after 30 mins
spring.datasource.hikari.idle-timeout=1800000
#name for the pool for better logging
spring.datasource.hikari.pool-name=ProductServicePool



# Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Commerce Tools
commercetools.project-key=mera-ecommerce
commercetools.client-id=nRVaIqtzG_nJS3pmoCD9gmuU
commercetools.client-secret=yt1rsF7U9omqN_2u4ig0k_4zGMk8rysk
commercetools.auth-url=https://auth.us-east-2.aws.commercetools.com
commercetools.api-url=https://api.us-east-2.aws.commercetools.com